---
- include: "custom/zsh.yml"
- include: "custom/nodejs.yml"
- include: "custom/elixir.yml"
- include: "custom/go.yml"
- include: "custom/python.yml"
- include: "custom/ruby.yml"
- include: "custom/kubernetes.yml"
- include: "custom/spark.yml"
