---
# custom/python

- name: update default python
  command: ~/.pyenv/bin/pyenv global {{ default_python_version }}

- name: update pyenv shims
  command: ~/.pyenv/bin/pyenv rehash

# custom/ruby

- name: update default ruby
  command: ~/.rbenv/bin/rbenv global {{ default_ruby_version }}

- name: update rbenv shims
  command: ~/.rbenv/bin/rbenv rehash

# custom/elixir

- name: update default erlang
  command: ~/.asdf/bin/asdf global erlang {{ default_erlang_version }}

- name: update erlang shims
  command: ~/.asdf/bin/asdf reshim erlang

- name: update default elixir
  command: ~/.asdf/bin/asdf global elixir {{ default_elixir_version }}

- name: update elixir shims
  command: ~/.asdf/bin/asdf reshim elixir
