---
brew_taps:
  - datawire/blackbird
  - hashicorp/tap

brew_packages:
  - asdf
  - autojump
  - ctags
  - fswatch
  - fzf
  - hashicorp/tap/terraform
  - htop
  - mas
  - minikube
  - neovim
  - terragrunt
  - the_silver_searcher
  - tree

cask_packages:
  - 1password
  - 1password-cli
  - alacritty
  - alfred
  - antigravity
  - arc
  - brave-browser
  - bruno
  - canva
  - discord
  - drawio
  - figma
  - firefox
  - font-jetbrains-mono
  - font-monaspace
  - google-drive
  - google-chrome
  - iterm2
  - keybase
  - mockoon
  - ngrok
  - notion
  - numi
  - spotify
  - telegram
  - visual-studio-code

mas_packages:
  - 441258766 # Magnet
  - 539883307 # LINE

# custom/zsh

zsh_packages:
  - zsh-autosuggestions
  - zsh-syntax-highlighting

# custom/nodejs

nodejs_versions:
  - 21.6.1

default_nodejs_version: 21.6.1

yarn_packages:
  - neovim
  - pm2
  - dockly

# custom/python

python_versions:
  - 3.12.3

default_python_version: 3.12.3

pip_packages:
  - pip
  - virtualenv
  - pipenv
  - pynvim
  - setuptools
  - wheel

# custom/ruby

ruby_versions:
  - 3.3.0

default_ruby_version: 3.3.0

gem_packages:
  - neovim
  - bundler
  - rails
  - pry

# custom/elixir

erlang_versions:
  - 27.2

elixir_versions:
  - 1.17.3-otp-27

default_erlang_version: 27.2
default_elixir_version: 1.17.3-otp-27

# custom/kubernetes

kubernetes_packages:
  - kubernetes-cli
  - helm
  - kubectx
