---
brew_taps:
  - homebrew/cask
  - homebrew/core
  - homebrew/cask-fonts
  - datawire/blackbird
  - heroku/brew

brew_packages:
  - autojump
  - awscli
  - ctags
  - exercism
  - fish
  - fswatch
  - fzf
  - gpg
  - heroku
  - htop
  - mas
  - minikube
  - neovim
  - postgresql
  - the_silver_searcher
  - tree

cask_packages:
  - 1password
  - alacritty
  - alfred
  - brave-browser
  - dash
  - discord
  - drawio
  - figma
  - firefox
  - font-jetbrains-mono
  - google-backup-and-sync
  - google-chrome
  - iterm2
  - messenger
  - numi
  - oracle-jdk
  - postman
  - slack
  - spotify
  - telegram
  - visual-studio-code
  - whatsapp

mas_packages:
  - 1091189122  # Bear
  - 441258766   # Magnet
  - 539883307   # LINE

# custom/zsh

zsh_packages:
  - zsh-autosuggestions
  - zsh-syntax-highlighting

# custom/nodejs

nodejs_versions:
  - 14.17.1

default_nodejs_version: 14.17.1

yarn_packages:
  - neovim
  - pm2
  - dockly

# custom/python

python_versions:
  - 3.9.1

default_python_version: 3.9.1

pip_packages:
  - pynvim
  - pip
  - virtualenv
  - pipenv
  - black

# custom/ruby

ruby_versions:
  - 2.7.2

default_ruby_version: 2.7.2

gem_packages:
  - neovim
  - bundler
  - rails
  - pry

# custom/elixir

erlang_versions:
  - 23.2.3

elixir_versions:
  - 1.12.1

default_erlang_version: 23.2.3
default_elixir_version: 1.12.1

# custom/kubernetes

kubernetes_packages:
  - kubernetes-cli
  - kubernetes-helm
  - kubectx
